# RT-Thread building script for component

Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Split('''
NXP/LPC18xx/Source/Templates/system_LPC18xx.c
''')
CPPPATH = [cwd + '/NXP/LPC18xx/Include', cwd + '/../CMSIS/Include']
# add for startup script 
if rtconfig.CROSS_TOOL == 'gcc':
		src += ['NXP/LPC18xx/Source/Templates/GCC/startup_LPC18xx.s']
elif rtconfig.CROSS_TOOL == 'keil':
		src += ['NXP/LPC18xx/Source/Templates/ARM/startup_LPC18xx.s']
elif rtconfig.CROSS_TOOL == 'iar':
		src += ['NXP/LPC18xx/Source/Templates/IAR/startup_LPC18xx.s']
group = DefineGroup('CMSIS', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
